version: "3.4"
services:
  grpc-client:
    build: grpc-client
    container_name: 'grpc-client'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8081:8081
    depends_on:
      - jaeger
    networks:
      - grpc-tracing-network

  grpc-server:
    build: grpc-server
    container_name: 'grpc-server'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8082:8082
    depends_on:
      - jaeger
    networks:
      - grpc-tracing-network

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - grpc-tracing-network
      
networks:
  grpc-tracing-network:
    driver: bridge